# Generated by Django 4.0.4 on 2022-05-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
